[project]
name = "complete-python-flask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.139.0",
    "jupyter>=1.1.1",
    "mlflow>=3.14.0",
    "numpy>=2.5.1",
    "pandas>=2.3.3",
    "scikit-learn>=1.9.0",
    "uvicorn>=0.50.2",
]
